### ISSUE TITLE
List of Stored Beer & Recipes

### ISSUE THREAD

**Issue by Amanda-Lacroix** [MSchuur/A-Brew-and-A-Bite#8]
Requirement
As an individual that just chose a wonderful beer and a delicious meal to complement it, I wish to store in a list my last 10 pairings.

Acceptance Criteria

Given that I have chosen a recipe and a beer. The last 10 recipe name and beer combinations that I generated are to be listed from local storage.
Given that when I click on an item in the list, the complete recipe and beer information will populate.

**Comment by MSchuur** [comment]
Moved the stored beers to the food genertation page. As the Edamam API did not give recipe instructions put did give a URL to the original recipe webpage it was decided to go to the URL in a new window. With that decision the stored beer were relocated to the food generation page and this page is being removed
